package synthesizer

import (
	"fmt"
	"strings"

	"github.com/abstractdevelopers/launchcore/buildpack/internal/planner"
)

// Synthesizer converts BuildPlan to optimized Dockerfile
type Synthesizer struct {
	indent string
}

// NewSynthesizer creates a new synthesizer
func NewSynthesizer() *Synthesizer {
	return &Synthesizer{
		indent: "    ",
	}
}

// Synthesize converts a BuildPlan to Dockerfile content
func (s *Synthesizer) Synthesize(plan *planner.BuildPlan) (string, error) {
	var lines []string

	// Handle user-supplied Dockerfile
	if plan.Strategy == "dockerfile_user_supplied" {
		return "", fmt.Errorf("user-supplied Dockerfile: no synthesis needed")
	}

	// Add header comment
	lines = append(lines, "# Generated by LaunchCore Buildpack")
	lines = append(lines, "# DO NOT EDIT - Changes will be overwritten")
	lines = append(lines, "")

	// Determine if multi-stage is needed
	needsMultiStage := len(plan.Stages) > 1

	if needsMultiStage {
		lines = s.synthesizeMultiStage(plan, lines)
	} else {
		lines = s.synthesizeSingleStage(plan, lines)
	}

	// Add healthcheck if applicable
	lines = s.addHealthCheck(lines, plan)

	return strings.Join(lines, "\n"), nil
}

func (s *Synthesizer) synthesizeMultiStage(plan *planner.BuildPlan, lines []string) []string {
	fromAliases := make(map[string]string)

	for i, stage := range plan.Stages {
		alias := fmt.Sprintf("stage%d", i)
		if i == len(plan.Stages)-1 {
			alias = "final"
		}
		fromAliases[stage.Name] = alias

		// Stage header
		if i > 0 {
			lines = append(lines, "")
		}
		lines = append(lines, fmt.Sprintf("FROM %s AS %s", stage.Image, alias))

		// Add metadata
		if stage.Name == "deps" || stage.Name == "builder" {
			lines = append(lines, s.indent+fmt.Sprintf("# Stage: %s - optimized for cache efficiency", stage.Name))
		}

		// Synthesize steps for this stage
		lines = s.synthesizeSteps(stage.Steps, lines, plan.CacheConfig)

		// Add cache mounts as comments (not directly supported in Dockerfile)
		if len(stage.Cache) > 0 {
			lines = append(lines, s.indent+fmt.Sprintf("# Cache mounts: %v", stage.Cache))
		}
	}

	// Final stage - copy from previous
	if len(plan.Stages) > 1 {
		lines = append(lines, "")
		lines = append(lines, "FROM "+plan.Stages[len(plan.Stages)-1].Image+" AS final")

		// Copy artifacts from builder stages
		for i := 0; i < len(plan.Stages)-1; i++ {
			alias := fmt.Sprintf("stage%d", i)
			stage := plan.Stages[i]

			// Copy output directory
			output := plan.Output
			if output == "" {
				output = "/app"
			}
			lines = append(lines, s.indent+fmt.Sprintf("COPY --from=%s %s /app", alias, output))
		}

		// Set workdir
		lines = append(lines, s.indent+"WORKDIR /app")

		// Add entrypoint
		if len(plan.Entrypoint) > 0 {
			lines = append(lines, s.indent+fmt.Sprintf("ENTRYPOINT %s", s.formatArray(plan.Entrypoint)))
		}
	}

	return lines
}

func (s *Synthesizer) synthesizeSingleStage(plan *planner.BuildPlan, lines []string) []string {
	runtime := plan.Runtime
	if runtime == "" {
		runtime = "alpine:latest"
	}

	lines = append(lines, fmt.Sprintf("FROM %s", runtime))

	// Set non-root user
	lines = append(lines, s.indent+"# Security: run as non-root user")
	lines = append(lines, s.indent+"RUN addgroup -g 1001 -S appgroup && adduser -u 1001 -S appuser -G appgroup")

	// Synthesize steps
	lines = s.synthesizeSteps(plan.Stages[0].Steps, lines, plan.CacheConfig)

	// Set workdir
	lines = append(lines, s.indent+"WORKDIR /app")

	// Switch to non-root user
	lines = append(lines, s.indent+"USER appuser")

	// Add entrypoint
	if len(plan.Entrypoint) > 0 {
		lines = append(lines, s.indent+fmt.Sprintf("ENTRYPOINT %s", s.formatArray(plan.Entrypoint)))
	}

	return lines
}

func (s *Synthesizer) synthesizeSteps(steps []planner.Step, lines []string, cache planner.CacheConfig) []string {
	var copyOrder []string // Track order of COPY for layer optimization

	for _, step := range steps {
		switch step.Type {
		case "copy":
			lines = append(lines, s.indent+fmt.Sprintf("COPY %s %s", step.Src, step.Dest))
			copyOrder = append(copyOrder, step.Src)

		case "run":
			// Split command for readability if too long
			if len(step.Command) > 80 {
				lines = append(lines, s.indent+"RUN \\")
				parts := strings.Split(step.Command, " && ")
				for _, part := range parts {
					lines = append(lines, s.indent+"    "+part+" \\")
				}
				lines[len(lines)-1] = strings.TrimSuffix(lines[len(lines)-1], " \\")
			} else {
				lines = append(lines, s.indent+fmt.Sprintf("RUN %s", step.Command))
			}

		case "workdir":
			lines = append(lines, s.indent+fmt.Sprintf("WORKDIR %s", step.Dest))

		case "env":
			parts := strings.SplitN(step.Command, "=", 2)
			if len(parts) == 2 {
				lines = append(lines, s.indent+fmt.Sprintf("ENV %s=%s", parts[0], parts[1]))
			}
		}
	}

	return lines
}

func (s *Synthesizer) addHealthCheck(lines []string, plan *planner.Plan) []string {
	// Add basic healthcheck based on port
	if plan.Metadata.Port > 0 {
		lines = append(lines, "")
		lines = append(lines, s.indent+fmt.Sprintf("# Health check on port %d", plan.Metadata.Port))
		lines = append(lines, s.indent+fmt.Sprintf("HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\"))
		lines = append(lines, s.indent+fmt.Sprintf("    CMD wget --no-verbose --tries=1 --spider http://localhost:%d/ || exit 1", plan.Metadata.Port))
	}
	return lines
}

func (s *Synthesizer) formatArray(arr []string) string {
	if len(arr) == 0 {
		return "[]"
	}
	quoted := make([]string, len(arr))
	for i, v := range arr {
		quoted[i] = fmt.Sprintf(`"%s"`, v)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
