package synthesizer

import (
	"fmt"
	"strings"

	"github.com/abstractdevelopers/launchcore/buildpack/internal/planner"
)

// Synthesizer converts BuildPlan to optimized Dockerfile
type Synthesizer struct {
	indent       string
	buildPackEnv string
}

// NewSynthesizer creates a new synthesizer
func NewSynthesizer() *Synthesizer {
	return &Synthesizer{
		indent:       "    ",
		buildPackEnv: "LAUNCHPACK",
	}
}

// Synthesize converts a BuildPlan to Dockerfile content
func (s *Synthesizer) Synthesize(plan *planner.BuildPlan) (string, error) {
	var lines []string

	// Header
	lines = append(lines, "# syntax=docker/dockerfile:1")
	lines = append(lines, "# Generated by LaunchPack - DO NOT EDIT")
	lines = append(lines, "")

	// Handle user-supplied Dockerfile
	if plan.Strategy == "dockerfile_user_supplied" {
		return "", fmt.Errorf("user-supplied Dockerfile")
	}

	// ARG for build version
	lines = append(lines, "# Build metadata")
	lines = append(lines, s.arg("BUILDPLATFORM")+"\n")
	lines = append(lines, s.comment("ARG LAUNCHPACK_BUILD_VERSION"))
	lines = append(lines, s.env("LAUNCHPACK_BUILD_VERSION", "${BUILDPLATFORM}-${BUILD_DATE}"))
	lines = append(lines, "")

	// Generate stages
	lines = s.generateStages(plan, lines)

	// Final image with healthcheck
	lines = s.addHealthcheck(plan, lines)

	return strings.Join(lines, "\n"), nil
}

func (s *Synthesizer) generateStages(plan *planner.BuildPlan, lines []string) []string {
	if len(plan.Stages) == 0 {
		return lines
	}

	for i, stage := range plan.Stages {
		alias := fmt.Sprintf("builder%d", i)
		if i == len(plan.Stages)-1 {
			alias = "final"
		}

		lines = append(lines, "")
		
		// Stage header
		if i > 0 {
			lines = append(lines, fmt.Sprintf("# ===== Stage %d: %s =====", i, stage.Name))
		} else {
			lines = append(lines, fmt.Sprintf("# ===== Stage: %s =====", stage.Name))
		}

		// FROM with platform
		if stage.Image != "" {
			lines = append(lines, fmt.Sprintf("FROM --platform=$BUILDPLATFORM %s AS %s", stage.Image, alias))
		}

		// Environment variables for this stage
		if stage.Name == "deps" || stage.Name == "builder" {
			lines = append(lines, s.comment("Cache mounts for dependency layers"))
			for _, mount := range plan.Cache.Mounts {
				if mount.Type == "cache" {
					lines = append(lines, fmt.Sprintf("RUN --mount=type=cache,target=%s", mount.Target))
				}
			}
			lines = append(lines, "")
		}

		// Generate steps
		lines = s.generateSteps(stage, alias, lines)

		// Stage-specific optimizations
		if stage.Name == "deps" {
			lines = append(lines, s.comment("Dependency layer complete"))
		}
	}

	// Copy to final stage
	if len(plan.Stages) > 1 {
		lines = append(lines, "")
		lines = append(lines, "# ===== Final Stage =====")
		lines = append(lines, fmt.Sprintf("FROM %s AS final", plan.Runtime.Image))

		// Labels
		lines = append(lines, s.label("maintainer", "LaunchPack"))
		lines = append(lines, s.label("generated-by", "LaunchPack"))

		// Working directory
		if plan.Runtime.Workdir != "" {
			lines = append(lines, s.workdir(plan.Runtime.Workdir))
		}

		// Copy artifacts from all builder stages
		for i := 0; i < len(plan.Stages)-1; i++ {
			alias := fmt.Sprintf("builder%d", i)
			stage := plan.Stages[i]
			
			// Copy output directory
			output := plan.Output
			if output == "" {
				output = "/app"
			}
			lines = append(lines, fmt.Sprintf("COPY --from=%s %s .", alias, output))
		}

		// Environment variables
		for key, value := range plan.Runtime.EnvVars {
			lines = append(lines, s.env(key, value))
		}

		// User (security)
		lines = append(lines, "")
		lines = append(lines, s.comment("Run as non-root user"))
		lines = append(lines, s.run("adduser -D -u 1001 -s /bin/sh appuser && chown -R appuser /app"))
		lines = append(lines, s.user("appuser"))

		// Expose port
		if len(plan.Ports) > 0 {
			lines = append(lines, s.expose(plan.Ports[0]))
		}

		// Entrypoint
		if len(plan.Stages[len(plan.Stages)-1].Entrypoint) > 0 {
			lines = append(lines, s.entrypoint(plan.Stages[len(plan.Stages)-1].Entrypoint))
		} else if plan.StartCmd != "" {
			// Replace PORT placeholder
			startCmd := plan.StartCmd
			if len(plan.Ports) > 0 && strings.Contains(startCmd, "{{PORT}}") {
				startCmd = strings.ReplaceAll(startCmd, "{{PORT}}", fmt.Sprintf("%d", plan.Ports[0]))
			}
			lines = append(lines, s.cmd([]string{"sh", "-c", startCmd}))
		}
	}

	return lines
}

func (s *Synthesizer) generateSteps(stage planner.Stage, alias string, lines []string) []string {
	for _, step := range stage.Steps {
		switch step.Type {
		case "workdir":
			lines = append(lines, s.workdir(step.Dest))

		case "copy":
			lines = append(lines, s.copy(step.Src, step.Dest))

		case "run":
			lines = append(lines, s.run(step.Command))

		case "env":
			parts := strings.SplitN(step.Command, "=", 2)
			if len(parts) == 2 {
				lines = append(lines, s.env(parts[0], parts[1]))
			}

		case "mount":
			if step.Mount != nil && step.Mount.Type == "cache" {
				// Mount is handled at stage level
				continue
			}

		case "user":
			lines = append(lines, s.user(step.Command))

		case "label":
			lines = append(lines, s.label(step.Src, step.Dest))
		}
	}

	return lines
}

func (s *Synthesizer) addHealthcheck(plan *planner.BuildPlan, lines []string) []string {
	if len(plan.Ports) == 0 {
		return lines
	}

	port := plan.Ports[0]
	lines = append(lines, "")
	lines = append(lines, s.comment(fmt.Sprintf("Healthcheck on port %d", port)))
	lines = append(lines, fmt.Sprintf("HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:%d/ || exit 1", port))

	return lines
}

// Helper methods

func (s *Synthesizer) comment(text string) string {
	return s.indent + "# " + text
}

func (s *Synthesizer) arg(name string) string {
	return s.indent + fmt.Sprintf("ARG %s", name)
}

func (s *Synthesizer) env(key, value string) string {
	return s.indent + fmt.Sprintf("ENV %s=%s", key, value)
}

func (s *Synthesizer) label(key, value string) string {
	return s.indent + fmt.Sprintf("LABEL %s=\"%s\"", key, value)
}

func (s *Synthesizer) workdir(path string) string {
	return s.indent + fmt.Sprintf("WORKDIR %s", path)
}

func (s *Synthesizer) run(command string) string {
	return s.indent + fmt.Sprintf("RUN %s", command)
}

func (s *Synthesizer) copy(src, dest string) string {
	// Handle cross-stage copy: "stage:path"
	if strings.Contains(src, ":") && !strings.HasPrefix(src, ".") && !strings.HasPrefix(src, "/") {
		return s.indent + fmt.Sprintf("COPY --from=%s %s", src, dest)
	}
	return s.indent + fmt.Sprintf("COPY %s %s", src, dest)
}

func (s *Synthesizer) expose(port int) string {
	return s.indent + fmt.Sprintf("EXPOSE %d", port)
}

func (s *Synthesizer) user(name string) string {
	return s.indent + fmt.Sprintf("USER %s", name)
}

func (s *Synthesizer) entrypoint(cmd []string) string {
	return s.indent + fmt.Sprintf("ENTRYPOINT %s", s.formatArray(cmd))
}

func (s *Synthesizer) cmd(cmd []string) string {
	return s.indent + fmt.Sprintf("CMD %s", s.formatArray(cmd))
}

func (s *Synthesizer) formatArray(arr []string) string {
	if len(arr) == 0 {
		return "[]"
	}
	quoted := make([]string, len(arr))
	for i, v := range arr {
		quoted[i] = fmt.Sprintf(`"%s"`, v)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// GenerateBuildScript generates a shell script for Coolify integration
// This outputs the commands to run during build, respecting Coolify's build environment
func (s *Synthesizer) GenerateBuildScript(plan *planner.BuildPlan) string {
	var lines []string

	lines = append(lines, "#!/bin/bash")
	lines = append(lines, "# Generated by LaunchPack for Coolify")
	lines = append(lines, "")
	lines = append(lines, "set -e")
	lines = append(lines, "")

	// Set up environment
	if plan.InstallCmd != "" {
		lines = append(lines, fmt.Sprintf("# Install dependencies"))
		lines = append(lines, plan.InstallCmd)
		lines = append(lines, "")
	}

	// Build
	if plan.BuildCmd != "" {
		lines = append(lines, fmt.Sprintf("# Build"))
		lines = append(lines, plan.BuildCmd)
		lines = append(lines, "")
	}

	// Output plan info
	lines = append(lines, "# Plan metadata")
	lines = append(lines, fmt.Sprintf("echo 'Strategy: %s'", plan.Strategy))
	lines = append(lines, fmt.Sprintf("echo 'Output: %s'", plan.Output))
	lines = append(lines, fmt.Sprintf("echo 'Start Command: %s'", plan.StartCmd))

	return strings.Join(lines, "\n")
}
